name: Generate Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *" # once a day
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          github_user: mehedikhan3281
          theme: github_dark
          plugins: >
            stats,repos-per-language,most-commit-language

      - name: Deploy to image-source branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: image-source
          publish_dir: ./dist
