name: Generate Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *" # once a day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          USERNAME: mehedikhan3281
          BRANCH_NAME: "image-source"
          THEME: "github_dark"
          AUTO_PUSH: true
